const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

async function main() {
  await prisma.college.deleteMany({});
  await prisma.college.createMany({
    data: [
      {
        name: "VIT Vellore",
        location: "Vellore",
        state: "Tamil Nadu",
        fees: 200000,
        rating: 4.8,
        avgPackage: 9.5,
        highestPackage: 50,
        placementRate: 95,
        description: "Top private engineering college",
      },
      {
        name: "SRM University",
        location: "Chennai",
        state: "Tamil Nadu",
        fees: 180000,
        rating: 4.5,
        avgPackage: 8.0,
        highestPackage: 40,
        placementRate: 90,
        description: "Leading private university",
      },
      {
        name: "KL University",
        location: "Guntur",
        state: "Andhra Pradesh",
        fees: 150000,
        rating: 4.4,
        avgPackage: 7.5,
        highestPackage: 35,
        placementRate: 88,
        description: "Deemed to be University",
      },
      {
        name: "Amrita University",
        location: "Coimbatore",
        state: "Tamil Nadu",
        fees: 170000,
        rating: 4.6,
        avgPackage: 8.5,
        highestPackage: 45,
        placementRate: 92,
        description: "Multi-campus private university",
      },
      {
        name: "NIT Warangal",
        location: "Warangal",
        state: "Telangana",
        fees: 90000,
        rating: 4.9,
        avgPackage: 12,
        highestPackage: 60,
        placementRate: 98,
        description: "National Institute of Technology",
      },
      {
        name: "NIT Trichy",
        location: "Tiruchirappalli",
        state: "Tamil Nadu",
        fees: 95000,
        rating: 4.9,
        avgPackage: 13,
        highestPackage: 65,
        placementRate: 99,
        description: "Premier National Institute of Technology",
      },
      {
        name: "IIIT Hyderabad",
        location: "Hyderabad",
        state: "Telangana",
        fees: 220000,
        rating: 4.8,
        avgPackage: 15,
        highestPackage: 70,
        placementRate: 97,
        description: "International Institute of Information Technology",
      },
      {
        name: "JNTU Hyderabad",
        location: "Hyderabad",
        state: "Telangana",
        fees: 80000,
        rating: 4.7,
        avgPackage: 10,
        highestPackage: 55,
        placementRate: 96,
        description: "Jawaharlal Nehru Technological University",
      },
      {
        name: "CBIT",
        location: "Hyderabad",
        state: "Telangana",
        fees: 140000,
        rating: 4.0,
        avgPackage: 5.5,
        highestPackage: 26,
        placementRate: 80,
        description: "Chaitanya Bharathi Institute of Technology",
      },
      {
        name: "VNR VJIET",
        location: "Hyderabad",
        state: "Telangana",
        fees: 130000,
        rating: 4.1,
        avgPackage: 6.0,
        highestPackage: 28,
        placementRate: 82,
        description: "Vignana Jyothi Institute of Engineering and Technology",
      },
      {
        name: "GITAM",
        location: "Visakhapatnam",
        state: "Andhra Pradesh",
        fees: 160000,
        rating: 4.3,
        avgPackage: 7.0,
        highestPackage: 30,
        placementRate: 87,
        description: "Gandhi Institute of Technology and Management",
      },
      {
        name: "Mohan Babu University",
        location: "Tirupati",
        state: "Andhra Pradesh",
        fees: 120000,
        rating: 4.2,
        avgPackage: 6.5,
        highestPackage: 25,
        placementRate: 85,
        description: "Leading private university",
      },
      {
        name: "KLU Vijayawada",
        location: "Vijayawada",
        state: "Andhra Pradesh",
        fees: 155000,
        rating: 4.3,
        avgPackage: 7.2,
        highestPackage: 33,
        placementRate: 86,
        description: "Koneru Lakshmaiah Education Foundation",
      },
      {
        name: "VIT AP",
        location: "Amaravati",
        state: "Andhra Pradesh",
        fees: 190000,
        rating: 4.7,
        avgPackage: 9.0,
        highestPackage: 48,
        placementRate: 93,
        description: "Vellore Institute of Technology, AP",
      },
      {
        name: "SASTRA University",
        location: "Thanjavur",
        state: "Tamil Nadu",
        fees: 165000,
        rating: 4.5,
        avgPackage: 8.2,
        highestPackage: 42,
        placementRate: 91,
        description: "Shanmugha Arts, Science, Technology & Research Academy",
      },
    ],
  });

  console.log("Colleges Added Successfully");
}

main()
  .catch(console.error)
  .finally(async () => {
    await prisma.$disconnect();
  });